#!/usr/bin/python3
import os
import subprocess
from datetime import datetime
from login import *

site_dir = os.path.join(os.path.dirname(os.path.realpath(__file__)), "..", "_site")

# change to the _site directory (if it exists)
if not os.path.exists(site_dir):
    print("               GH: _site folder does not exist, exitting.")
    quit()

os.chdir(site_dir)
if not os.path.isdir(".git"):
    print("GH: .git directory not detected")
    subprocess.call(["git", "init"])
    subprocess.call(["git", "remote", "add", "origin", github_repo_origin])

subprocess.call(["git", "add", "-A"])
subprocess.call(["git", "commit", "-m", f"upload {datetime.now().strftime('%d/%m/%Y %H:%M:%S')}"])
subprocess.call(["git", "push", "-f", f"https://{github_token}@{github_repo_origin.replace('https://','')}"])
